### ISSUE TITLE
Support for nested objects: InvalidArgumentException: Invalid type "object"

### ISSUE THREAD

**Issue by agrizzli** [Articus/DataTransfer#1]
Hello Articus! Great library, thank you for making it available!

I'm using it in junction with PathHandler through generated code with OpenAPI generator. I created a simple nested object property in OpenAPI yaml:

```yaml
ExampleItem:
  # ...
  properties:
    example_object:
      type: object
```

This maps to a DTO object:

```php
class ExampleItem
{
    /**
     * @DTA\Data(field="example_object", nullable=true)
     * @DTA\Strategy(name="Object", options={"type":object::class})
     * @DTA\Validator(name="Dictionary", options={"type":object::class})
     * @var object
     */
    public $example_object;
}
```

I use it inside a ```Handler``` class for PathHandler library and try to return just new instantiated empty object:

```php
    /**
     * Get example item by id
     * @PHA\Get()
     * @PHA\Producer(name=PHProducer\Transfer::class, mediaType="application/json")
     * @param ServerRequestInterface $request
     * @return \App\DTO\ExampleItem
     */
    public function getExampleItem(ServerRequestInterface $request): \App\DTO\ExampleItem
    {
        return new App\DTO\ExampleItem();
    }
```  

This leads to following error:

```
InvalidArgumentException: Invalid type "object". in /home/agrizzli/Sites/joining_db_backend/vendor/articus/data-transfer/src/Articus/DataTransfer/Strategy/EmbeddedObject.php:31
Stack trace:...
```

When I just instantiate new ```ExampleItem``` object in other context, then there is no problem. When I delete object property from this DTO, then error disappears.

**Comment by Articus** [comment]
Hi, 
Well, definition 
```YAML
    example_object:
      type: object
```
is a bit obscure :) Normally it should have some property declarations and there will be a separate class that will describe example_object structure. And [EmbeddedObject hydration strategy](https://github.com/Articus/DataTransfer/blob/master/src/Articus/DataTransfer/Strategy/EmbeddedObject.php) requires that separate class name to do its work. Check [metadata examples](https://github.com/Articus/DataTransfer/blob/master/README.md#metadata) as reference or [tests](https://github.com/Articus/DataTransfer/blob/master/tests/functional/ServiceTest.php). 
If you really want some generic object without any restrictions, you need to create and use your own strategy implementing [this interface](https://github.com/Articus/DataTransfer/blob/master/src/Articus/DataTransfer/Strategy/StrategyInterface.php).

**Comment by agrizzli** [comment]
Yes, indeed, it was the idea to have some non-strictly-typed object for some kind of various data. I will take a look. Thanks!

**Comment by Articus** [comment]
So I guess the question is answered :) Closing this issue then.
